// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/message_cache.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/message_cache.go -destination=./internal/repository/mocks/message_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "go-template-microservice/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageCacheRepository is a mock of MessageCacheRepository interface.
type MockMessageCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageCacheRepositoryMockRecorder is the mock recorder for MockMessageCacheRepository.
type MockMessageCacheRepositoryMockRecorder struct {
	mock *MockMessageCacheRepository
}

// NewMockMessageCacheRepository creates a new mock instance.
func NewMockMessageCacheRepository(ctrl *gomock.Controller) *MockMessageCacheRepository {
	mock := &MockMessageCacheRepository{ctrl: ctrl}
	mock.recorder = &MockMessageCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageCacheRepository) EXPECT() *MockMessageCacheRepositoryMockRecorder {
	return m.recorder
}

// CacheSentMessage mocks base method.
func (m *MockMessageCacheRepository) CacheSentMessage(ctx context.Context, message models.SentMessageCache) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheSentMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheSentMessage indicates an expected call of CacheSentMessage.
func (mr *MockMessageCacheRepositoryMockRecorder) CacheSentMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheSentMessage", reflect.TypeOf((*MockMessageCacheRepository)(nil).CacheSentMessage), ctx, message)
}

// GetAllSentMessages mocks base method.
func (m *MockMessageCacheRepository) GetAllSentMessages(ctx context.Context, limit int) ([]models.SentMessageCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSentMessages", ctx, limit)
	ret0, _ := ret[0].([]models.SentMessageCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSentMessages indicates an expected call of GetAllSentMessages.
func (mr *MockMessageCacheRepositoryMockRecorder) GetAllSentMessages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSentMessages", reflect.TypeOf((*MockMessageCacheRepository)(nil).GetAllSentMessages), ctx, limit)
}
