// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/repository.go -destination=./internal/repository/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "go-template-microservice/internal/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetMessageCacheRepository mocks base method.
func (m *MockIRepository) GetMessageCacheRepository() repository.MessageCacheRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageCacheRepository")
	ret0, _ := ret[0].(repository.MessageCacheRepository)
	return ret0
}

// GetMessageCacheRepository indicates an expected call of GetMessageCacheRepository.
func (mr *MockIRepositoryMockRecorder) GetMessageCacheRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageCacheRepository", reflect.TypeOf((*MockIRepository)(nil).GetMessageCacheRepository))
}

// GetMessageRepository mocks base method.
func (m *MockIRepository) GetMessageRepository() repository.MessageRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageRepository")
	ret0, _ := ret[0].(repository.MessageRepository)
	return ret0
}

// GetMessageRepository indicates an expected call of GetMessageRepository.
func (mr *MockIRepositoryMockRecorder) GetMessageRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageRepository", reflect.TypeOf((*MockIRepository)(nil).GetMessageRepository))
}
