// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/message_sender.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/message_sender.go -destination=./internal/services/mocks/message_sender_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	response "go-template-microservice/internal/resources/response"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageSenderService is a mock of MessageSenderService interface.
type MockMessageSenderService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderServiceMockRecorder
	isgomock struct{}
}

// MockMessageSenderServiceMockRecorder is the mock recorder for MockMessageSenderService.
type MockMessageSenderServiceMockRecorder struct {
	mock *MockMessageSenderService
}

// NewMockMessageSenderService creates a new mock instance.
func NewMockMessageSenderService(ctrl *gomock.Controller) *MockMessageSenderService {
	mock := &MockMessageSenderService{ctrl: ctrl}
	mock.recorder = &MockMessageSenderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSenderService) EXPECT() *MockMessageSenderServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMessageSenderService) Send(ctx context.Context, to, content string) (*response.WebhookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, content)
	ret0, _ := ret[0].(*response.WebhookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMessageSenderServiceMockRecorder) Send(ctx, to, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessageSenderService)(nil).Send), ctx, to, content)
}
